<?php /** @var Market\ShippingSurcharge\Block\Adminhtml\Shipping\View $block */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>

<?php /* Surcharge */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-content">
        <?php if ($block->isShippingSurchargeEnabled()): ?>
            <strong><?php echo __('Additional Shipping Charge:'); ?></strong>
            <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($order->getData(\Market\ShippingSurcharge\Model\Surcharge::SURCHARGE), true); ?>
        <?php endif; ?>
    </div>
</div>
